// Code generated by a Template
using System;
using log4net;

namespace DNX.Helpers.Log4Net
{
    /// <summary>
    /// Class LogExtensions for Fatal
    /// </summary>
    public static partial class LogExtensions
    {
        /// <summary>
        /// Writes a Fatal message, if Fatal is enabled
        /// </summary>
        /// <param name="logger">The logger.</param>
        /// <param name="messageText">The messageText.</param>
        public static void FatalFunc(this ILog logger, Func<string> messageText)
        {
            if (logger.IsFatalEnabled)
            {
                logger.Fatal(messageText());
            }
        }

        /// <summary>
        /// Writes a Fatal message with Exception, if Fatal is enabled
        /// </summary>
        /// <param name="logger">The logger.</param>
        /// <param name="messageText">The message text.</param>
        /// <param name="exception">The exception.</param>
        public static void FatalFunc(this ILog logger, Func<string> messageText, Func<Exception> exception)
        {
            if (logger.IsFatalEnabled)
            {
                logger.Fatal(messageText(), exception());
            }
        }
	}
}
