// Code generated by a Template
using System;
using log4net;

namespace DNX.Helpers.Log4Net
{
    /// <summary>
    /// Class LogExtensions for Error
    /// </summary>
    public static partial class LogExtensions
    {
        /// <summary>
        /// Writes a Error message, if Error is enabled
        /// </summary>
        /// <param name="logger">The logger.</param>
        /// <param name="messageText">The messageText.</param>
        public static void ErrorFunc(this ILog logger, Func<string> messageText)
        {
            if (logger.IsErrorEnabled)
            {
                logger.Error(messageText());
            }
        }

        /// <summary>
        /// Writes a Error message with Exception, if Error is enabled
        /// </summary>
        /// <param name="logger">The logger.</param>
        /// <param name="messageText">The message text.</param>
        /// <param name="exception">The exception.</param>
        public static void ErrorFunc(this ILog logger, Func<string> messageText, Func<Exception> exception)
        {
            if (logger.IsErrorEnabled)
            {
                logger.Error(messageText(), exception());
            }
        }
	}
}
