// Code generated by a Template
using System;
using log4net;

namespace DNX.Helpers.Log4Net
{
    /// <summary>
    /// Class LogExtensions for Warn
    /// </summary>
    public static partial class LogExtensions
    {
        /// <summary>
        /// Writes a Warn message, if Warn is enabled
        /// </summary>
        /// <param name="logger">The logger.</param>
        /// <param name="messageText">The messageText.</param>
        public static void WarnFunc(this ILog logger, Func<string> messageText)
        {
            if (logger.IsWarnEnabled)
            {
                logger.Warn(messageText());
            }
        }

        /// <summary>
        /// Writes a Warn message with Exception, if Warn is enabled
        /// </summary>
        /// <param name="logger">The logger.</param>
        /// <param name="messageText">The message text.</param>
        /// <param name="exception">The exception.</param>
        public static void WarnFunc(this ILog logger, Func<string> messageText, Func<Exception> exception)
        {
            if (logger.IsWarnEnabled)
            {
                logger.Warn(messageText(), exception());
            }
        }
	}
}
